/**
 * Tests for Report Generator
 */

import { describe, it, expect } from 'vitest';
import {
  generateReport,
  exportToText,
  exportToHTML,
  exportToJSON,
  exportReport,
} from '@/lib/comparison/reportGenerator';
import { compareDocuments } from '@/lib/comparison/comparisonEngine';
import type { DocumentInfo, ReportFormat } from '@/lib/comparison/types';

describe('Report Generator', () => {
  const doc1Info: DocumentInfo = { name: 'original.pdf', pageCount: 2 };
  const doc2Info: DocumentInfo = { name: 'revised.pdf', pageCount: 2 };

  const createTestResult = () => {
    const doc1Text = ['Hello World', 'Page 2 content'];
    const doc2Text = ['Hello Universe', 'Page 2 content'];
    return compareDocuments(doc1Text, doc2Text, doc1Info, doc2Info);
  };

  describe('generateReport', () => {
    it('should generate a report from comparison result', () => {
      const result = createTestResult();
      const report = generateReport(result);

      expect(report.title).toContain('original.pdf');
      expect(report.title).toContain('revised.pdf');
      expect(report.generatedAt).toBeDefined();
      expect(report.result).toBe(result);
    });

    it('should respect includeVisualDiff option', () => {
      const result = createTestResult();
      const report = generateReport(result, { includeVisualDiff: true });

      expect(report.includeVisualDiff).toBe(true);
    });

    it('should respect includeThumbnails option', () => {
      const result = createTestResult();
      const report = generateReport(result, { includeThumbnails: true });

      expect(report.includeThumbnails).toBe(true);
    });
  });

  describe('exportToText', () => {
    it('should export report to text format', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const text = exportToText(report);

      expect(text).toContain('DOCUMENT COMPARISON REPORT');
      expect(text).toContain('original.pdf');
      expect(text).toContain('revised.pdf');
      expect(text).toContain('SUMMARY');
    });

    it('should include change statistics', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const text = exportToText(report);

      expect(text).toContain('Overall Similarity');
      expect(text).toContain('Total Changes');
    });

    it('should include page details', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const text = exportToText(report);

      expect(text).toContain('PAGE DETAILS');
    });

    it('should include footer', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const text = exportToText(report);

      expect(text).toContain('Generated by PaperFlow');
    });
  });

  describe('exportToHTML', () => {
    it('should export report to HTML format', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const html = exportToHTML(report);

      expect(html).toContain('<!DOCTYPE html>');
      expect(html).toContain('<html');
      expect(html).toContain('</html>');
    });

    it('should include document names', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const html = exportToHTML(report);

      expect(html).toContain('original.pdf');
      expect(html).toContain('revised.pdf');
    });

    it('should include summary statistics', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const html = exportToHTML(report);

      expect(html).toContain('Overall Similarity');
      expect(html).toContain('Total Changes');
    });

    it('should include CSS styling', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const html = exportToHTML(report);

      expect(html).toContain('<style>');
      expect(html).toContain('</style>');
    });

    it('should escape HTML in document names', () => {
      const maliciousInfo: DocumentInfo = { name: '<script>alert("xss")</script>.pdf', pageCount: 1 };
      const result = compareDocuments(['text'], ['text'], maliciousInfo, doc2Info);
      const report = generateReport(result);
      const html = exportToHTML(report);

      expect(html).not.toContain('<script>alert("xss")</script>');
      expect(html).toContain('&lt;script&gt;');
    });
  });

  describe('exportToJSON', () => {
    it('should export report to JSON format', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const json = exportToJSON(report);

      expect(() => JSON.parse(json)).not.toThrow();
    });

    it('should contain all report data', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const json = exportToJSON(report);
      const parsed = JSON.parse(json);

      expect(parsed.title).toBe(report.title);
      expect(parsed.generatedAt).toBe(report.generatedAt);
      expect(parsed.result).toBeDefined();
    });

    it('should be pretty-printed', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const json = exportToJSON(report);

      expect(json).toContain('\n');
      expect(json).toContain('  '); // Indentation
    });
  });

  describe('exportReport', () => {
    it('should export to text format', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const output = exportReport(report, 'text');

      expect(output).toContain('DOCUMENT COMPARISON REPORT');
    });

    it('should export to HTML format', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const output = exportReport(report, 'html');

      expect(output).toContain('<!DOCTYPE html>');
    });

    it('should export to JSON format', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const output = exportReport(report, 'json');

      expect(() => JSON.parse(output)).not.toThrow();
    });

    it('should export to PDF format (returns HTML for printing)', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const output = exportReport(report, 'pdf');

      // PDF export currently returns HTML for print-to-PDF
      expect(output).toContain('<!DOCTYPE html>');
    });

    it('should default to text format for unknown format', () => {
      const result = createTestResult();
      const report = generateReport(result);
      const output = exportReport(report, 'unknown' as ReportFormat);

      expect(output).toContain('DOCUMENT COMPARISON REPORT');
    });
  });
});
