/**
 * Report Generator
 * Generates comparison reports in various formats.
 */

import type {
  ComparisonResult,
  ComparisonReport,
  ReportFormat,
  ChangeType,
} from './types';

/**
 * Generate a comparison report
 */
export function generateReport(
  result: ComparisonResult,
  options: {
    includeVisualDiff?: boolean;
    includeThumbnails?: boolean;
  } = {}
): ComparisonReport {
  return {
    title: `Comparison: ${result.document1.name} vs ${result.document2.name}`,
    generatedAt: Date.now(),
    result,
    includeVisualDiff: options.includeVisualDiff ?? false,
    includeThumbnails: options.includeThumbnails ?? false,
  };
}

/**
 * Export report to text format
 */
export function exportToText(report: ComparisonReport): string {
  const { result } = report;
  const lines: string[] = [];

  // Header
  lines.push('=' .repeat(60));
  lines.push('DOCUMENT COMPARISON REPORT');
  lines.push('=' .repeat(60));
  lines.push('');

  // Document info
  lines.push('Documents Compared:');
  lines.push(`  Document 1: ${result.document1.name} (${result.document1.pageCount} pages)`);
  lines.push(`  Document 2: ${result.document2.name} (${result.document2.pageCount} pages)`);
  lines.push('');

  // Summary
  lines.push('-'.repeat(60));
  lines.push('SUMMARY');
  lines.push('-'.repeat(60));
  lines.push(`Overall Similarity: ${result.summary.overallSimilarity}%`);
  lines.push(`Pages Compared: ${result.summary.pagesCompared}`);
  lines.push(`Total Changes: ${result.summary.totalTextChanges}`);
  lines.push(`  - Added: ${result.summary.addedCount}`);
  lines.push(`  - Removed: ${result.summary.removedCount}`);
  lines.push(`  - Modified: ${result.summary.modifiedCount}`);
  if (result.summary.movedCount > 0) {
    lines.push(`  - Moved: ${result.summary.movedCount}`);
  }
  lines.push('');

  // Page-by-page details
  lines.push('-'.repeat(60));
  lines.push('PAGE DETAILS');
  lines.push('-'.repeat(60));

  for (const page of result.pages) {
    if (page.textChanges.length > 0) {
      lines.push('');
      lines.push(`Page ${page.pageNumber} (${page.similarity}% similar)`);
      lines.push(`  Changes: ${page.textChanges.length}`);

      for (const change of page.textChanges) {
        const symbol = getChangeSymbol(change.type);
        const text = truncateText(change.text, 50);
        lines.push(`    ${symbol} ${text}`);
      }
    }
  }

  // Footer
  lines.push('');
  lines.push('-'.repeat(60));
  lines.push(`Report generated: ${new Date(report.generatedAt).toISOString()}`);
  lines.push('Generated by PaperFlow');

  return lines.join('\n');
}

/**
 * Export report to HTML format
 */
export function exportToHTML(report: ComparisonReport): string {
  const { result } = report;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(report.title)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 2rem; }
    h1 { color: #1e3a5f; }
    .summary { background: #f5f5f5; padding: 1rem; border-radius: 8px; margin: 1rem 0; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; }
    .stat { text-align: center; padding: 1rem; background: white; border-radius: 4px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .stat-value { font-size: 2rem; font-weight: bold; color: #3b82f6; }
    .stat-label { color: #666; font-size: 0.875rem; }
    .page { margin: 1.5rem 0; padding: 1rem; border: 1px solid #e0e0e0; border-radius: 8px; }
    .page-header { display: flex; justify-content: space-between; margin-bottom: 1rem; }
    .page-title { font-weight: bold; }
    .similarity { color: #666; }
    .changes { list-style: none; padding: 0; margin: 0; }
    .change { padding: 0.5rem; margin: 0.25rem 0; border-radius: 4px; }
    .change-added { background: #dcfce7; border-left: 4px solid #22c55e; }
    .change-removed { background: #fee2e2; border-left: 4px solid #ef4444; }
    .change-modified { background: #fef3c7; border-left: 4px solid #f59e0b; }
    .change-symbol { font-family: monospace; margin-right: 0.5rem; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; color: #666; font-size: 0.875rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(report.title)}</h1>

  <div class="summary">
    <h2>Summary</h2>
    <div class="stats">
      <div class="stat">
        <div class="stat-value">${result.summary.overallSimilarity}%</div>
        <div class="stat-label">Overall Similarity</div>
      </div>
      <div class="stat">
        <div class="stat-value">${result.summary.totalTextChanges}</div>
        <div class="stat-label">Total Changes</div>
      </div>
      <div class="stat">
        <div class="stat-value">${result.summary.addedCount}</div>
        <div class="stat-label">Added</div>
      </div>
      <div class="stat">
        <div class="stat-value">${result.summary.removedCount}</div>
        <div class="stat-label">Removed</div>
      </div>
      <div class="stat">
        <div class="stat-value">${result.summary.modifiedCount}</div>
        <div class="stat-label">Modified</div>
      </div>
    </div>
    <p><strong>Document 1:</strong> ${escapeHtml(result.document1.name)} (${result.document1.pageCount} pages)</p>
    <p><strong>Document 2:</strong> ${escapeHtml(result.document2.name)} (${result.document2.pageCount} pages)</p>
  </div>

  <h2>Page Details</h2>
  ${result.pages
    .filter((page) => page.textChanges.length > 0)
    .map(
      (page) => `
    <div class="page">
      <div class="page-header">
        <span class="page-title">Page ${page.pageNumber}</span>
        <span class="similarity">${page.similarity}% similar</span>
      </div>
      <ul class="changes">
        ${page.textChanges
          .map(
            (change) => `
          <li class="change change-${change.type}">
            <span class="change-symbol">${getChangeSymbol(change.type)}</span>
            ${escapeHtml(truncateText(change.text, 100))}
          </li>
        `
          )
          .join('')}
      </ul>
    </div>
  `
    )
    .join('')}

  <div class="footer">
    <p>Report generated: ${new Date(report.generatedAt).toISOString()}</p>
    <p>Generated by PaperFlow</p>
  </div>
</body>
</html>`;
}

/**
 * Export report to JSON format
 */
export function exportToJSON(report: ComparisonReport): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Export report to specified format
 */
export function exportReport(report: ComparisonReport, format: ReportFormat): string {
  switch (format) {
    case 'text':
      return exportToText(report);
    case 'html':
      return exportToHTML(report);
    case 'json':
      return exportToJSON(report);
    case 'pdf':
      // PDF generation would require pdf-lib integration
      // For now, return HTML that can be printed to PDF
      return exportToHTML(report);
    default:
      return exportToText(report);
  }
}

/**
 * Get symbol for change type
 */
function getChangeSymbol(type: ChangeType): string {
  switch (type) {
    case 'added':
      return '+';
    case 'removed':
      return '-';
    case 'modified':
      return '~';
    case 'moved':
      return '>';
    default:
      return '?';
  }
}

/**
 * Truncate text to max length
 */
function truncateText(text: string, maxLength: number): string {
  const singleLine = text.replace(/\n/g, ' ').trim();
  if (singleLine.length <= maxLength) return singleLine;
  return singleLine.substring(0, maxLength - 3) + '...';
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m] || m);
}

/**
 * Download report as file
 */
export function downloadReport(
  report: ComparisonReport,
  format: ReportFormat,
  filename?: string
): void {
  const content = exportReport(report, format);
  const extension = format === 'text' ? 'txt' : format;
  const mimeType =
    format === 'html'
      ? 'text/html'
      : format === 'json'
        ? 'application/json'
        : 'text/plain';

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `comparison-report.${extension}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
